# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dsid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dsid.proto',
  package='dsid',
  syntax='proto3',
  serialized_pb=_b('\n\ndsid.proto\x12\x04\x64sid\"A\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x0c\n\x04nUSP\x18\x04 \x01(\x05\"\r\n\x0bVoidRequest\"\x0b\n\tVoidReply\"\x1e\n\x0bLongRequest\x12\x0f\n\x07message\x18\x01 \x01(\x03\"\x1c\n\tLongReply\x12\x0f\n\x07message\x18\x01 \x01(\x03\"\xb0\x01\n\x0e\x42igLongRequest\x12\x12\n\nparameter1\x18\x01 \x01(\x03\x12\x12\n\nparameter2\x18\x02 \x01(\x03\x12\x12\n\nparameter3\x18\x03 \x01(\x03\x12\x12\n\nparameter4\x18\x04 \x01(\x03\x12\x12\n\nparameter5\x18\x05 \x01(\x03\x12\x12\n\nparameter6\x18\x06 \x01(\x03\x12\x12\n\nparameter7\x18\x07 \x01(\x03\x12\x12\n\nparameter8\x18\x08 \x01(\x03\"\x1f\n\x0c\x42igLongReply\x12\x0f\n\x07message\x18\x01 \x01(\x03\" \n\rStringRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0bStringReply\x12\x0f\n\x07message\x18\x01 \x01(\t\",\n\rObjectRequest\x12\x1b\n\x07message\x18\x01 \x01(\x0b\x32\n.dsid.User\"*\n\x0bObjectReply\x12\x1b\n\x07message\x18\x01 \x01(\x0b\x32\n.dsid.User2\xc2\x02\n\x04\x44SID\x12\x39\n\x11SendsVoidResponse\x12\x11.dsid.VoidRequest\x1a\x0f.dsid.VoidReply\"\x00\x12\x39\n\x11SendsLongResponse\x12\x11.dsid.LongRequest\x1a\x0f.dsid.LongReply\"\x00\x12\x42\n\x14SendsBigLongResponse\x12\x14.dsid.BigLongRequest\x1a\x12.dsid.BigLongReply\"\x00\x12?\n\x13SendsStringResponse\x12\x13.dsid.StringRequest\x1a\x11.dsid.StringReply\"\x00\x12?\n\x13SendsObjectResponse\x12\x13.dsid.ObjectRequest\x1a\x11.dsid.ObjectReply\"\x00\x62\x06proto3')
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='dsid.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='dsid.User.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastname', full_name='dsid.User.lastname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='dsid.User.age', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nUSP', full_name='dsid.User.nUSP', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=85,
)


_VOIDREQUEST = _descriptor.Descriptor(
  name='VoidRequest',
  full_name='dsid.VoidRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=100,
)


_VOIDREPLY = _descriptor.Descriptor(
  name='VoidReply',
  full_name='dsid.VoidReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=113,
)


_LONGREQUEST = _descriptor.Descriptor(
  name='LongRequest',
  full_name='dsid.LongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='dsid.LongRequest.message', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=145,
)


_LONGREPLY = _descriptor.Descriptor(
  name='LongReply',
  full_name='dsid.LongReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='dsid.LongReply.message', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=175,
)


_BIGLONGREQUEST = _descriptor.Descriptor(
  name='BigLongRequest',
  full_name='dsid.BigLongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameter1', full_name='dsid.BigLongRequest.parameter1', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameter2', full_name='dsid.BigLongRequest.parameter2', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameter3', full_name='dsid.BigLongRequest.parameter3', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameter4', full_name='dsid.BigLongRequest.parameter4', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameter5', full_name='dsid.BigLongRequest.parameter5', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameter6', full_name='dsid.BigLongRequest.parameter6', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameter7', full_name='dsid.BigLongRequest.parameter7', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameter8', full_name='dsid.BigLongRequest.parameter8', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=354,
)


_BIGLONGREPLY = _descriptor.Descriptor(
  name='BigLongReply',
  full_name='dsid.BigLongReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='dsid.BigLongReply.message', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=387,
)


_STRINGREQUEST = _descriptor.Descriptor(
  name='StringRequest',
  full_name='dsid.StringRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='dsid.StringRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=421,
)


_STRINGREPLY = _descriptor.Descriptor(
  name='StringReply',
  full_name='dsid.StringReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='dsid.StringReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=453,
)


_OBJECTREQUEST = _descriptor.Descriptor(
  name='ObjectRequest',
  full_name='dsid.ObjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='dsid.ObjectRequest.message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=499,
)


_OBJECTREPLY = _descriptor.Descriptor(
  name='ObjectReply',
  full_name='dsid.ObjectReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='dsid.ObjectReply.message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=543,
)

_OBJECTREQUEST.fields_by_name['message'].message_type = _USER
_OBJECTREPLY.fields_by_name['message'].message_type = _USER
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['VoidRequest'] = _VOIDREQUEST
DESCRIPTOR.message_types_by_name['VoidReply'] = _VOIDREPLY
DESCRIPTOR.message_types_by_name['LongRequest'] = _LONGREQUEST
DESCRIPTOR.message_types_by_name['LongReply'] = _LONGREPLY
DESCRIPTOR.message_types_by_name['BigLongRequest'] = _BIGLONGREQUEST
DESCRIPTOR.message_types_by_name['BigLongReply'] = _BIGLONGREPLY
DESCRIPTOR.message_types_by_name['StringRequest'] = _STRINGREQUEST
DESCRIPTOR.message_types_by_name['StringReply'] = _STRINGREPLY
DESCRIPTOR.message_types_by_name['ObjectRequest'] = _OBJECTREQUEST
DESCRIPTOR.message_types_by_name['ObjectReply'] = _OBJECTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsid.User)
  ))
_sym_db.RegisterMessage(User)

VoidRequest = _reflection.GeneratedProtocolMessageType('VoidRequest', (_message.Message,), dict(
  DESCRIPTOR = _VOIDREQUEST,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsid.VoidRequest)
  ))
_sym_db.RegisterMessage(VoidRequest)

VoidReply = _reflection.GeneratedProtocolMessageType('VoidReply', (_message.Message,), dict(
  DESCRIPTOR = _VOIDREPLY,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsid.VoidReply)
  ))
_sym_db.RegisterMessage(VoidReply)

LongRequest = _reflection.GeneratedProtocolMessageType('LongRequest', (_message.Message,), dict(
  DESCRIPTOR = _LONGREQUEST,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsid.LongRequest)
  ))
_sym_db.RegisterMessage(LongRequest)

LongReply = _reflection.GeneratedProtocolMessageType('LongReply', (_message.Message,), dict(
  DESCRIPTOR = _LONGREPLY,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsid.LongReply)
  ))
_sym_db.RegisterMessage(LongReply)

BigLongRequest = _reflection.GeneratedProtocolMessageType('BigLongRequest', (_message.Message,), dict(
  DESCRIPTOR = _BIGLONGREQUEST,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsid.BigLongRequest)
  ))
_sym_db.RegisterMessage(BigLongRequest)

BigLongReply = _reflection.GeneratedProtocolMessageType('BigLongReply', (_message.Message,), dict(
  DESCRIPTOR = _BIGLONGREPLY,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsid.BigLongReply)
  ))
_sym_db.RegisterMessage(BigLongReply)

StringRequest = _reflection.GeneratedProtocolMessageType('StringRequest', (_message.Message,), dict(
  DESCRIPTOR = _STRINGREQUEST,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsid.StringRequest)
  ))
_sym_db.RegisterMessage(StringRequest)

StringReply = _reflection.GeneratedProtocolMessageType('StringReply', (_message.Message,), dict(
  DESCRIPTOR = _STRINGREPLY,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsid.StringReply)
  ))
_sym_db.RegisterMessage(StringReply)

ObjectRequest = _reflection.GeneratedProtocolMessageType('ObjectRequest', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTREQUEST,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsid.ObjectRequest)
  ))
_sym_db.RegisterMessage(ObjectRequest)

ObjectReply = _reflection.GeneratedProtocolMessageType('ObjectReply', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTREPLY,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsid.ObjectReply)
  ))
_sym_db.RegisterMessage(ObjectReply)



_DSID = _descriptor.ServiceDescriptor(
  name='DSID',
  full_name='dsid.DSID',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=546,
  serialized_end=868,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendsVoidResponse',
    full_name='dsid.DSID.SendsVoidResponse',
    index=0,
    containing_service=None,
    input_type=_VOIDREQUEST,
    output_type=_VOIDREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendsLongResponse',
    full_name='dsid.DSID.SendsLongResponse',
    index=1,
    containing_service=None,
    input_type=_LONGREQUEST,
    output_type=_LONGREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendsBigLongResponse',
    full_name='dsid.DSID.SendsBigLongResponse',
    index=2,
    containing_service=None,
    input_type=_BIGLONGREQUEST,
    output_type=_BIGLONGREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendsStringResponse',
    full_name='dsid.DSID.SendsStringResponse',
    index=3,
    containing_service=None,
    input_type=_STRINGREQUEST,
    output_type=_STRINGREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendsObjectResponse',
    full_name='dsid.DSID.SendsObjectResponse',
    index=4,
    containing_service=None,
    input_type=_OBJECTREQUEST,
    output_type=_OBJECTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DSID)

DESCRIPTOR.services_by_name['DSID'] = _DSID

# @@protoc_insertion_point(module_scope)
